name: Radio Phonic Audio
favicon: null
layout_spectrum: 0.92367
typography_spectrum: 0.341
title: Radio Phonic Audio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6e9bf'
    - '#532800'
    - '#e4b076'
    - '#9b7d54'
    - '#744f2b'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
